### ISSUE TITLE
Testing request

### ISSUE THREAD

**Issue by linslin** [CottaCush/yii2-utils#7]
Hi m8, this https://github.com/CottaCush/yii2-utils/pull/6 should be fixed by default now. Could you test if yii2-curl v1.1.2  https://github.com/linslin/Yii2-Curl/releases/tag/1.1.2 build/test** works on UNIX/Windows now?

THX
Lin

**Comment by yemexx1** [comment]
Hi @linslin. Tests work on Unix(Mac OS). We should integrate travis.

![codeception yml - yii2-curl - -library-webserver-documents-yii2-curl 2017-03-29 11-03-25](https://cloud.githubusercontent.com/assets/2228873/24449699/1b2fd64e-1470-11e7-9a2a-fbed43389f94.png)

**Comment by linslin** [comment]
Looking great, I run this tests on Windows and it does work. =)
